name: DeployMain

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install composer Dependencies
        run: php composer.phar update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Run Migrations
        run: php artisan migrate --force

      #      - name: Run Tests
      #        run: php artisan test

      - name: Deploy PHP to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.API_FOLDER }}
            git checkout main
            git pull origin main
            php composer.phar update
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
            php artisan optimize:clear